import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import MenubarComponent from "./components/MenubarComponent/MenubarComponent";

export const metadata: Metadata = {
  title: "Insight API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>
          <MenubarComponent />
          <div className="common-styling">
            {children}
          </div>
        </ClientLayout>
      </body>
    </html>
  );
}
