import type { Metadata } from "next";
import "./globals.css";
import ClientLayout from "./Providers/ClientLayout";

export const metadata: Metadata = {
  title: "Insight API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
